version: "3.8"
services:
    mongodb:
      image: mongo
      container_name: mongodb
      environment:
            MONGO_INITDB_ROOT_USERNAME: dap
            MONGO_INITDB_ROOT_PASSWORD: dap
            MONGO_INITDB_DATABASE: dap
      ports:
            - 27017-27019:27017-27019
      volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      restart: unless-stopped